### ISSUE TITLE
Connection error despite connecting ok

### ISSUE THREAD

**Issue by rnbrady** [rkalis/electrum-cli#1]
Got this error:

<img width="978" alt="Screenshot 2020-12-04 at 17 27 00" src="https://user-images.githubusercontent.com/625766/101197963-ae0d5d00-365a-11eb-9a61-dbdd066feaab.png">

Will submit a PR.

**Comment by rnbrady** [comment]
To reproduce this just upgrade the dependency:

```
yarn add electrum-cash@2.0.6
./index.js --bch server.ping
```

If dependencies might have breaking changes in patch level versions, then `npm shrinkwrap` might be a solution.

**Comment by rkalis** [comment]
Fix is live in 0.1.1
